/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_rafaelajuria;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author rajur
 */
public class GUI extends javax.swing.JFrame {
        Boolean AgregandoVehiculo = false;
        Boolean ModificandoVehiculo = false;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        //<editor-fold defaultstate="collapsed" desc=" Codigo Adicional - Corre al iniciar el programa ">
        //Llena la tabla con todos los datos
        DatabaseCon DB = new DatabaseCon("./Volkswagen.accdb");
        DB.Connect();
        try
        {
         DB.Query.execute("SELECT Vehiculos.VIN, Vehiculos.Marca, Vehiculos.Categoria, Vehiculos.Carroceria, Vehiculos.[Numero de Puertas], Vehiculos.Color, Vehiculos.[Tipo de Motor], Vehiculos.Precio, Vehiculos.[Tipo de Hibridacion], Vehiculos.[Cantidad Maxima de Pasajeros], Vehiculos.[Tiempo de ensamblaje] FROM Vehiculos");
         ResultSet Result = DB.Query.getResultSet();
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.setRowCount(0);
         int i =0;
         while (Result.next()) 
         {
         model.addRow(new Object[]{null,null,null,null,null});
         jTable1.setValueAt(Result.getString(1),i,0);
         jTable1.setValueAt(Result.getString(2),i,1);
         jTable1.setValueAt(Result.getString(3),i,2);
         jTable1.setValueAt(Result.getString(6),i,3);
         jTable1.setValueAt(Result.getString(8),i,4);
         i++;
         } 
        }
        catch (SQLException ex) 
                {
                ex.printStackTrace();
                }
        DB.Disconnect();
        
        //
        
        //</editor-fold>
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Filtro = new javax.swing.ButtonGroup();
        jPopupMenu_ContextMenu = new javax.swing.JPopupMenu();
        jMenuItem_AgregarVehiculo = new javax.swing.JMenuItem();
        jMenuItem_ModificarVehiculo = new javax.swing.JMenuItem();
        jMenuItem_EliminarVehiculo = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Atributos = new javax.swing.JLabel();
        jLabel_VINTXT = new javax.swing.JLabel();
        jTextField_VIN = new javax.swing.JTextField();
        jLabel_MarcaTXT = new javax.swing.JLabel();
        jRadioButton_AtrSEAT = new javax.swing.JRadioButton();
        jRadioButton_AtrSkoda = new javax.swing.JRadioButton();
        jRadioButton_AtrAudi = new javax.swing.JRadioButton();
        jRadioButton_AtrVolkswagen = new javax.swing.JRadioButton();
        jRadioButton_Porsche = new javax.swing.JRadioButton();
        jRadioButton_Lambo = new javax.swing.JRadioButton();
        jRadioButton_ATRBugatti = new javax.swing.JRadioButton();
        jRadioButton_AtrBentley = new javax.swing.JRadioButton();
        jLabel_CategoriaTXT = new javax.swing.JLabel();
        jRadioButton_AtrGeneralista = new javax.swing.JRadioButton();
        jRadioButton_AtrPremium = new javax.swing.JRadioButton();
        jRadioButton_AtrDeportivo = new javax.swing.JRadioButton();
        jRadioButton_AtrHatchback = new javax.swing.JRadioButton();
        jRadioButton_AtrFastBack = new javax.swing.JRadioButton();
        jRadioButton_AtrSUV = new javax.swing.JRadioButton();
        jRadioButton_AtrFamiliar = new javax.swing.JRadioButton();
        jRadioButtonAtr_Sedan = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner_NumPuertas = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton_AtrColorBlanco = new javax.swing.JRadioButton();
        jRadioButton_AtrColorNegro = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton_AtrMotorCombustion = new javax.swing.JRadioButton();
        jRadioButton_AtrMotorElectrico = new javax.swing.JRadioButton();
        jSpinner_Precio = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jButton_GuardarVehiculo = new javax.swing.JButton();
        buttonGroup_Marca = new javax.swing.ButtonGroup();
        buttonGroup_Categoria = new javax.swing.ButtonGroup();
        buttonGroup_Carroceria = new javax.swing.ButtonGroup();
        buttonGroup_Color = new javax.swing.ButtonGroup();
        buttonGroup_Motor = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_FiltroSeleccionadoTXT = new javax.swing.JLabel();
        jLabel_FiltroSeleccionado = new javax.swing.JLabel();
        jButton_AplicarFiltro = new javax.swing.JButton();
        jButton_EliminarFiltro = new javax.swing.JButton();
        jMenuBar_MenuPrincipal = new javax.swing.JMenuBar();
        jMenu_MenuFiltros = new javax.swing.JMenu();
        jMenu_FiltroMarcas = new javax.swing.JMenu();
        jRadioButtonMenuItem_Audi = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Bentley = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Bugatti = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Lamborghini = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Porsche = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Seat = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Skoda = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Volkswagen = new javax.swing.JRadioButtonMenuItem();
        jMenu_Categoria = new javax.swing.JMenu();
        jRadioButtonMenuItem_Generalista = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Premium = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Deportivo = new javax.swing.JRadioButtonMenuItem();
        jMenu_Carroceria = new javax.swing.JMenu();
        jRadioButtonMenuItem_Sedan = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Familiar = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_HatchBack = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_FastBack = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_SUV = new javax.swing.JRadioButtonMenuItem();
        jMenu_Color = new javax.swing.JMenu();
        jRadioButtonMenuItem_Blanco = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Negro = new javax.swing.JRadioButtonMenuItem();
        jMenu_TipoDeMotor = new javax.swing.JMenu();
        jRadioButtonMenuItem_Combustion = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Eletrico = new javax.swing.JRadioButtonMenuItem();
        jMenu_BusquedaManual = new javax.swing.JMenu();
        jMenuItem_BusquedaVIN = new javax.swing.JMenuItem();
        jMenuItem_AddDefault = new javax.swing.JMenuItem();

        jMenuItem_AgregarVehiculo.setText("Agregar");
        jMenuItem_AgregarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AgregarVehiculoActionPerformed(evt);
            }
        });
        jPopupMenu_ContextMenu.add(jMenuItem_AgregarVehiculo);

        jMenuItem_ModificarVehiculo.setText("Modificar");
        jMenuItem_ModificarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ModificarVehiculoActionPerformed(evt);
            }
        });
        jPopupMenu_ContextMenu.add(jMenuItem_ModificarVehiculo);

        jMenuItem_EliminarVehiculo.setText("Eliminar");
        jMenuItem_EliminarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_EliminarVehiculoActionPerformed(evt);
            }
        });
        jPopupMenu_ContextMenu.add(jMenuItem_EliminarVehiculo);

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);

        jLabel_Atributos.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel_Atributos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Atributos.setText("Atributos del Vehiculo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Atributos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Atributos, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel_VINTXT.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_VINTXT.setText("VIN:");

        jLabel_MarcaTXT.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_MarcaTXT.setText("Marca:");

        buttonGroup_Marca.add(jRadioButton_AtrSEAT);
        jRadioButton_AtrSEAT.setText("SEAT");

        buttonGroup_Marca.add(jRadioButton_AtrSkoda);
        jRadioButton_AtrSkoda.setText("Skoda");

        buttonGroup_Marca.add(jRadioButton_AtrAudi);
        jRadioButton_AtrAudi.setText("Audi");

        buttonGroup_Marca.add(jRadioButton_AtrVolkswagen);
        jRadioButton_AtrVolkswagen.setText("Volkswagen");

        buttonGroup_Marca.add(jRadioButton_Porsche);
        jRadioButton_Porsche.setText("Porsche");

        buttonGroup_Marca.add(jRadioButton_Lambo);
        jRadioButton_Lambo.setText("Lamborghini");

        buttonGroup_Marca.add(jRadioButton_ATRBugatti);
        jRadioButton_ATRBugatti.setText("Bugatti");

        buttonGroup_Marca.add(jRadioButton_AtrBentley);
        jRadioButton_AtrBentley.setText("Bentley");

        jLabel_CategoriaTXT.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_CategoriaTXT.setText("Categoria:");

        buttonGroup_Categoria.add(jRadioButton_AtrGeneralista);
        jRadioButton_AtrGeneralista.setText("Generalista");

        buttonGroup_Categoria.add(jRadioButton_AtrPremium);
        jRadioButton_AtrPremium.setText("Premium");

        buttonGroup_Categoria.add(jRadioButton_AtrDeportivo);
        jRadioButton_AtrDeportivo.setText("Deportivo");

        buttonGroup_Carroceria.add(jRadioButton_AtrHatchback);
        jRadioButton_AtrHatchback.setText("HatchBack");

        buttonGroup_Carroceria.add(jRadioButton_AtrFastBack);
        jRadioButton_AtrFastBack.setText("FastBack");

        buttonGroup_Carroceria.add(jRadioButton_AtrSUV);
        jRadioButton_AtrSUV.setText("SUV");

        buttonGroup_Carroceria.add(jRadioButton_AtrFamiliar);
        jRadioButton_AtrFamiliar.setText("Familiar");

        buttonGroup_Carroceria.add(jRadioButtonAtr_Sedan);
        jRadioButtonAtr_Sedan.setText("Sedan");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Carroceria");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Numero de Puertas:");

        jSpinner_NumPuertas.setModel(new javax.swing.SpinnerNumberModel(2, 2, 5, 1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Color:");

        buttonGroup_Color.add(jRadioButton_AtrColorBlanco);
        jRadioButton_AtrColorBlanco.setText("Blanco");

        buttonGroup_Color.add(jRadioButton_AtrColorNegro);
        jRadioButton_AtrColorNegro.setText("Negro");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Tipo de Motor:");

        buttonGroup_Motor.add(jRadioButton_AtrMotorCombustion);
        jRadioButton_AtrMotorCombustion.setText("Combustion");

        buttonGroup_Motor.add(jRadioButton_AtrMotorElectrico);
        jRadioButton_AtrMotorElectrico.setText("Electrico");

        jSpinner_Precio.setModel(new javax.swing.SpinnerNumberModel(50000.0d, 20000.0d, 500000.0d, 10000.0d));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Precio:");

        jButton_GuardarVehiculo.setText("Guardar");
        jButton_GuardarVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_GuardarVehiculoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel_VINTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_VIN, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel_MarcaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_AtrSEAT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_ATRBugatti))
                    .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialog1Layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addComponent(jRadioButton_AtrAudi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton_AtrVolkswagen)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioButton_AtrBentley))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                            .addComponent(jRadioButton_AtrSkoda)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton_Porsche)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton_Lambo)))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_CategoriaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_AtrDeportivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_AtrPremium)
                            .addComponent(jRadioButton_AtrGeneralista)))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonAtr_Sedan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_AtrFamiliar))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_AtrMotorElectrico)
                            .addComponent(jRadioButton_AtrMotorCombustion)))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_AtrHatchback)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addComponent(jRadioButton_AtrFastBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_AtrSUV))
                            .addComponent(jSpinner_NumPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_AtrColorNegro)
                            .addComponent(jRadioButton_AtrColorBlanco)))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner_Precio, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton_GuardarVehiculo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_VIN)
                    .addComponent(jLabel_VINTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_MarcaTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton_AtrSEAT)
                    .addComponent(jRadioButton_ATRBugatti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_AtrAudi)
                    .addComponent(jRadioButton_AtrVolkswagen)
                    .addComponent(jRadioButton_AtrBentley))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_Porsche)
                    .addComponent(jRadioButton_Lambo)
                    .addComponent(jRadioButton_AtrSkoda))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CategoriaTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton_AtrGeneralista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_AtrPremium)
                    .addComponent(jRadioButton_AtrDeportivo))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonAtr_Sedan)
                    .addComponent(jRadioButton_AtrFamiliar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_AtrHatchback)
                    .addComponent(jRadioButton_AtrFastBack)
                    .addComponent(jRadioButton_AtrSUV))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner_NumPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_AtrColorBlanco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_AtrColorNegro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_AtrMotorCombustion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_AtrMotorElectrico)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jButton_GuardarVehiculo)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel_Titulo.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("Base de datos de Ensamblaje");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "VIN", "Marca", "Categoria", "Color", "Precio"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel_FiltroSeleccionadoTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FiltroSeleccionadoTXT.setText("Filtro Seleccionado:");

        jLabel_FiltroSeleccionado.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel_FiltroSeleccionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FiltroSeleccionado.setText("Ninguno");

        jButton_AplicarFiltro.setText("Aplicar");
        jButton_AplicarFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_AplicarFiltroMouseClicked(evt);
            }
        });

        jButton_EliminarFiltro.setText("Quitar");
        jButton_EliminarFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_EliminarFiltroMouseClicked(evt);
            }
        });

        jMenu_MenuFiltros.setText("Filtros");

        jMenu_FiltroMarcas.setText("Marca");

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Audi);
        jRadioButtonMenuItem_Audi.setText("Audi");
        jMenu_FiltroMarcas.add(jRadioButtonMenuItem_Audi);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Bentley);
        jRadioButtonMenuItem_Bentley.setText("Bentley");
        jMenu_FiltroMarcas.add(jRadioButtonMenuItem_Bentley);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Bugatti);
        jRadioButtonMenuItem_Bugatti.setText("Bugatti");
        jMenu_FiltroMarcas.add(jRadioButtonMenuItem_Bugatti);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Lamborghini);
        jRadioButtonMenuItem_Lamborghini.setText("Lamborghini");
        jMenu_FiltroMarcas.add(jRadioButtonMenuItem_Lamborghini);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Porsche);
        jRadioButtonMenuItem_Porsche.setText("Porsche");
        jMenu_FiltroMarcas.add(jRadioButtonMenuItem_Porsche);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Seat);
        jRadioButtonMenuItem_Seat.setText("SEAT");
        jMenu_FiltroMarcas.add(jRadioButtonMenuItem_Seat);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Skoda);
        jRadioButtonMenuItem_Skoda.setText("Skoda");
        jMenu_FiltroMarcas.add(jRadioButtonMenuItem_Skoda);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Volkswagen);
        jRadioButtonMenuItem_Volkswagen.setText("Volkswagen");
        jMenu_FiltroMarcas.add(jRadioButtonMenuItem_Volkswagen);

        jMenu_MenuFiltros.add(jMenu_FiltroMarcas);

        jMenu_Categoria.setText("Categoria");

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Generalista);
        jRadioButtonMenuItem_Generalista.setText("Generalista");
        jMenu_Categoria.add(jRadioButtonMenuItem_Generalista);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Premium);
        jRadioButtonMenuItem_Premium.setText("Premium");
        jMenu_Categoria.add(jRadioButtonMenuItem_Premium);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Deportivo);
        jRadioButtonMenuItem_Deportivo.setText("Deportivos");
        jMenu_Categoria.add(jRadioButtonMenuItem_Deportivo);

        jMenu_MenuFiltros.add(jMenu_Categoria);

        jMenu_Carroceria.setText("Carroceria");

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Sedan);
        jRadioButtonMenuItem_Sedan.setText("Sedan");
        jMenu_Carroceria.add(jRadioButtonMenuItem_Sedan);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Familiar);
        jRadioButtonMenuItem_Familiar.setText("Familiar");
        jMenu_Carroceria.add(jRadioButtonMenuItem_Familiar);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_HatchBack);
        jRadioButtonMenuItem_HatchBack.setText("HatchBack");
        jMenu_Carroceria.add(jRadioButtonMenuItem_HatchBack);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_FastBack);
        jRadioButtonMenuItem_FastBack.setText("FastBack");
        jMenu_Carroceria.add(jRadioButtonMenuItem_FastBack);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_SUV);
        jRadioButtonMenuItem_SUV.setText("SUV");
        jMenu_Carroceria.add(jRadioButtonMenuItem_SUV);

        jMenu_MenuFiltros.add(jMenu_Carroceria);

        jMenu_Color.setText("Color");

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Blanco);
        jRadioButtonMenuItem_Blanco.setText("Blanco");
        jMenu_Color.add(jRadioButtonMenuItem_Blanco);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Negro);
        jRadioButtonMenuItem_Negro.setText("Negro");
        jMenu_Color.add(jRadioButtonMenuItem_Negro);

        jMenu_MenuFiltros.add(jMenu_Color);

        jMenu_TipoDeMotor.setText("Tipo de Motor");

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Combustion);
        jRadioButtonMenuItem_Combustion.setText("Combustion");
        jMenu_TipoDeMotor.add(jRadioButtonMenuItem_Combustion);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Eletrico);
        jRadioButtonMenuItem_Eletrico.setText("Electrico");
        jMenu_TipoDeMotor.add(jRadioButtonMenuItem_Eletrico);

        jMenu_MenuFiltros.add(jMenu_TipoDeMotor);

        jMenuBar_MenuPrincipal.add(jMenu_MenuFiltros);

        jMenu_BusquedaManual.setText("Busqueda");

        jMenuItem_BusquedaVIN.setText("VIN");
        jMenuItem_BusquedaVIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_BusquedaVINActionPerformed(evt);
            }
        });
        jMenu_BusquedaManual.add(jMenuItem_BusquedaVIN);

        jMenuItem_AddDefault.setText("Agregar Predeterminado");
        jMenuItem_AddDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AddDefaultActionPerformed(evt);
            }
        });
        jMenu_BusquedaManual.add(jMenuItem_AddDefault);

        jMenuBar_MenuPrincipal.add(jMenu_BusquedaManual);

        setJMenuBar(jMenuBar_MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_FiltroSeleccionadoTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton_AplicarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_EliminarFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                            .addComponent(jLabel_FiltroSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_FiltroSeleccionadoTXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_FiltroSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AplicarFiltro)
                    .addComponent(jButton_EliminarFiltro))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(evt.isMetaDown())
        {
           try
            {
            jPopupMenu_ContextMenu.show(evt.getComponent(), evt.getX(), evt.getY());
            }
            catch(Exception e)
                   {    
                   }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItem_EliminarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_EliminarVehiculoActionPerformed
        // TODO add your handling code here:
        try
        {
        String VIN =String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        DatabaseCon DB = new DatabaseCon("./Volkswagen.accdb");
        DB.Connect();
        try
        {
         DB.Query.execute("DELETE FROM Vehiculos WHERE VIN=\""+VIN+"\"");
         DB.Commit();
        } 
        catch (SQLException ex) 
        {
            ex.printStackTrace();
        }
        DB.Disconnect();
        }
        catch(Exception e)
               {    
               }
        DatabaseCon DB = new DatabaseCon("./Volkswagen.accdb");
        DB.Connect();
        try
        {
         DB.Query.execute("SELECT Vehiculos.VIN, Vehiculos.Marca, Vehiculos.Categoria, Vehiculos.Carroceria, Vehiculos.[Numero de Puertas], Vehiculos.Color, Vehiculos.[Tipo de Motor], Vehiculos.Precio, Vehiculos.[Tipo de Hibridacion], Vehiculos.[Cantidad Maxima de Pasajeros], Vehiculos.[Tiempo de ensamblaje] FROM Vehiculos");
         ResultSet Result = DB.Query.getResultSet();
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.setRowCount(0);
         int i =0;
         while (Result.next()) 
         {
         model.addRow(new Object[]{null,null,null,null,null});
         jTable1.setValueAt(Result.getString(1),i,0);
         jTable1.setValueAt(Result.getString(2),i,1);
         jTable1.setValueAt(Result.getString(3),i,2);
         jTable1.setValueAt(Result.getString(6),i,3);
         jTable1.setValueAt(Result.getString(8),i,4);
         i++;
         } 
        }
        catch (SQLException ex) 
                {
                ex.printStackTrace();
                }
        DB.Disconnect();
    }//GEN-LAST:event_jMenuItem_EliminarVehiculoActionPerformed

    private void jMenuItem_BusquedaVINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_BusquedaVINActionPerformed
        // TODO add your handling code here:
        String VIN = JOptionPane.showInputDialog("Ingrese el VIN que desea ver");
        jLabel_FiltroSeleccionado.setText("VIN="+VIN);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        DatabaseCon DB2 = new DatabaseCon("./Volkswagen.accdb");
        DB2.Connect();
        try
        {
         DB2.Query.execute("SELECT Vehiculos.VIN, Vehiculos.Marca, Vehiculos.Categoria, Vehiculos.Carroceria, Vehiculos.[Numero de Puertas], Vehiculos.Color, Vehiculos.[Tipo de Motor], Vehiculos.Precio, Vehiculos.[Tipo de Hibridacion], Vehiculos.[Cantidad Maxima de Pasajeros], Vehiculos.[Tiempo de ensamblaje] FROM Vehiculos WHERE VIN=\""+VIN+"\"");
         ResultSet Result = DB2.Query.getResultSet();
         
         int i =0;
         while (Result.next()) 
         {
         model.addRow(new Object[]{null,null,null,null,null});
         jTable1.setValueAt(Result.getString(1),i,0);
         jTable1.setValueAt(Result.getString(2),i,1);
         jTable1.setValueAt(Result.getString(3),i,2);
         jTable1.setValueAt(Result.getString(6),i,3);
         jTable1.setValueAt(Result.getString(8),i,4);
         i++;
         } 
         
        }
        catch (SQLException ex) 
                {
                ex.printStackTrace();
                }
        DB2.Disconnect();
    }//GEN-LAST:event_jMenuItem_BusquedaVINActionPerformed

    private void jButton_AplicarFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AplicarFiltroMouseClicked
        // TODO add your handling code here:
        String TipoDeFiltro="Color";
        String Filtro="Blanco";
        
        
        //Seleccion de Filtros
        if(jRadioButtonMenuItem_Audi.isSelected())
        {
            TipoDeFiltro="Marca"; Filtro="Audi";
        } 
        if(jRadioButtonMenuItem_Bentley.isSelected())
        {
            TipoDeFiltro="Marca"; Filtro="Bentley";
        } 
        if(jRadioButtonMenuItem_Bugatti.isSelected())
        {
            TipoDeFiltro="Marca"; Filtro="Bugatti";
        } 
        if(jRadioButtonMenuItem_Deportivo.isSelected())
        {
            TipoDeFiltro="Categoria"; Filtro="Deportivo";
        } 
        if(jRadioButtonMenuItem_FastBack.isSelected())
        {
            TipoDeFiltro="Carroceria"; Filtro="Fastback";
        } 
        if(jRadioButtonMenuItem_Familiar.isSelected())
        {
            TipoDeFiltro="Carroceria"; Filtro="Familiar";
        } 
        if(jRadioButtonMenuItem_Generalista.isSelected())
        {
            TipoDeFiltro="Categoria"; Filtro="Generalista";
        } 
        if(jRadioButtonMenuItem_Lamborghini.isSelected())
        {
            TipoDeFiltro="Marca"; Filtro="Lamborghini";
        } 
        if(jRadioButtonMenuItem_HatchBack.isSelected())
        {
            TipoDeFiltro="Carroceria"; Filtro="HatchBack";
        } 
        if(jRadioButtonMenuItem_Porsche.isSelected())
        {
            TipoDeFiltro="Marca"; Filtro="Porsche";
        } 
        if(jRadioButtonMenuItem_Premium.isSelected())
        {
            TipoDeFiltro="Categoria"; Filtro="Premium";
        } 
        if(jRadioButtonMenuItem_Seat.isSelected())
        {
            TipoDeFiltro="Marca"; Filtro="SEAT";
        } 
        if(jRadioButtonMenuItem_SUV.isSelected())
        {
            TipoDeFiltro="Carroceria"; Filtro="SUV";
        } 
        if(jRadioButtonMenuItem_Sedan.isSelected())
        {
            TipoDeFiltro="Carroceria"; Filtro="Sedan";
        } 
        if(jRadioButtonMenuItem_Skoda.isSelected())
        {
            TipoDeFiltro="Marca"; Filtro="Skoda";
        } 
        if(jRadioButtonMenuItem_Volkswagen.isSelected())
        {
            TipoDeFiltro="Marca"; Filtro="Volkswagen";
        } 
        if(jRadioButtonMenuItem_Blanco.isSelected())
        {
            TipoDeFiltro="Color"; Filtro="Blanco";
        } 
        if(jRadioButtonMenuItem_Negro.isSelected())
        {
            TipoDeFiltro="Color"; Filtro="Negro";
        } 
        if(jRadioButtonMenuItem_Combustion.isSelected())
        {
            TipoDeFiltro="[Tipo de Motor]"; Filtro="Combustion";
        } 
        if(jRadioButtonMenuItem_Eletrico.isSelected())
        {
            TipoDeFiltro="[Tipo de Motor]"; Filtro="Electrico";
        } 
        jLabel_FiltroSeleccionado.setText(TipoDeFiltro+"="+Filtro);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        DatabaseCon DB2 = new DatabaseCon("./Volkswagen.accdb");
        DB2.Connect();
        try
        {
         DB2.Query.execute("SELECT Vehiculos.VIN, Vehiculos.Marca, Vehiculos.Categoria, Vehiculos.Carroceria, Vehiculos.[Numero de Puertas], Vehiculos.Color, Vehiculos.[Tipo de Motor], Vehiculos.Precio, Vehiculos.[Tipo de Hibridacion], Vehiculos.[Cantidad Maxima de Pasajeros], Vehiculos.[Tiempo de ensamblaje] FROM Vehiculos WHERE "+TipoDeFiltro+"=\""+Filtro+"\"");
         ResultSet Result = DB2.Query.getResultSet();
         
         int i =0;
         while (Result.next()) 
         {
         model.addRow(new Object[]{null,null,null,null,null});
         jTable1.setValueAt(Result.getString(1),i,0);
         jTable1.setValueAt(Result.getString(2),i,1);
         jTable1.setValueAt(Result.getString(3),i,2);
         jTable1.setValueAt(Result.getString(6),i,3);
         jTable1.setValueAt(Result.getString(8),i,4);
         i++;
         } 
         
        }
        catch (SQLException ex) 
                {
                ex.printStackTrace();
                }
        DB2.Disconnect();
    }//GEN-LAST:event_jButton_AplicarFiltroMouseClicked

    private void jButton_EliminarFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_EliminarFiltroMouseClicked
        // TODO add your handling code here:
        jLabel_FiltroSeleccionado.setText("Ninguno");
        DatabaseCon DB = new DatabaseCon("./Volkswagen.accdb");
        DB.Connect();
        try
        {
         DB.Query.execute("SELECT Vehiculos.VIN, Vehiculos.Marca, Vehiculos.Categoria, Vehiculos.Carroceria, Vehiculos.[Numero de Puertas], Vehiculos.Color, Vehiculos.[Tipo de Motor], Vehiculos.Precio, Vehiculos.[Tipo de Hibridacion], Vehiculos.[Cantidad Maxima de Pasajeros], Vehiculos.[Tiempo de ensamblaje] FROM Vehiculos");
         ResultSet Result = DB.Query.getResultSet();
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.setRowCount(0);
         int i =0;
         while (Result.next()) 
         {
         model.addRow(new Object[]{null,null,null,null,null});
         jTable1.setValueAt(Result.getString(1),i,0);
         jTable1.setValueAt(Result.getString(2),i,1);
         jTable1.setValueAt(Result.getString(3),i,2);
         jTable1.setValueAt(Result.getString(6),i,3);
         jTable1.setValueAt(Result.getString(8),i,4);
         i++;
         } 
        }
        catch (SQLException ex) 
                {
                ex.printStackTrace();
                }
        DB.Disconnect();
    }//GEN-LAST:event_jButton_EliminarFiltroMouseClicked

    private void jMenuItem_AgregarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AgregarVehiculoActionPerformed
        // TODO add your handling code here:
        jDialog1.pack();
        jDialog1.setVisible(true);
        jTextField_VIN.enable(true);
        AgregandoVehiculo=true;
    }//GEN-LAST:event_jMenuItem_AgregarVehiculoActionPerformed

    private void jButton_GuardarVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_GuardarVehiculoMouseClicked
        // TODO add your handling code here:
        String VIN = jTextField_VIN.getText();
        //Marca
        String Marca="";
        if(jRadioButton_ATRBugatti.isSelected())
            Marca="Bugatti";
        if(jRadioButton_AtrAudi.isSelected())
            Marca="Audi";
        if(jRadioButton_AtrSEAT.isSelected())
            Marca="SEAT";
        if(jRadioButton_AtrVolkswagen.isSelected())
            Marca="Volkswagen";
        if(jRadioButton_Lambo.isSelected())
            Marca="Lamborghini";
        if(jRadioButton_Porsche.isSelected())
            Marca="Porsche";
        if(jRadioButton_AtrSkoda.isSelected())
            Marca="Skoda";
        if(jRadioButton_AtrBentley.isSelected())
            Marca="Bentley";
        //Categoria
        String Categoria="";
        if(jRadioButton_AtrDeportivo.isSelected())
            Categoria="Deportivo";
        if(jRadioButton_AtrGeneralista.isSelected())
            Categoria="Generalista";
        if(jRadioButton_AtrPremium.isSelected())
            Categoria="Premium";
        //Carroceria
        String Carroceria ="";
        if(jRadioButton_AtrFamiliar.isSelected())
            Carroceria="Familiar";
        if(jRadioButton_AtrFastBack.isSelected())
            Carroceria="FastBack";
        if(jRadioButton_AtrHatchback.isSelected())
            Carroceria="HatchBack";
        if(jRadioButton_AtrSUV.isSelected())
            Carroceria="SUV";
        if(jRadioButtonAtr_Sedan.isSelected())
            Carroceria="Sedan";
        //NumPuertas
        int NumPuertas = (Integer) jSpinner_NumPuertas.getValue();
        //Color
        String Color="";
        if(jRadioButton_AtrColorBlanco.isSelected())
            Color = "Blanco";
        if(jRadioButton_AtrColorNegro.isSelected())
            Color = "Negro";
        //Motor
        String Motor="";
        if(jRadioButton_AtrMotorElectrico.isSelected())
            Motor="Electrico";
        if(jRadioButton_AtrMotorCombustion.isSelected())
            Motor="Combustion";
        //Precio
        double Precio = (Double) jSpinner_Precio.getValue();
        
        
        
        if(AgregandoVehiculo)
        {
        DatabaseCon DB = new DatabaseCon("./Volkswagen.accdb");
        DB.Connect();
        try
        {
         DB.Query.execute("INSERT INTO Vehiculos(Vehiculos.VIN, Vehiculos.Marca, Vehiculos.Categoria, Vehiculos.Carroceria, Vehiculos.[Numero de Puertas], Vehiculos.Color, Vehiculos.[Tipo de Motor], Vehiculos.Precio, Vehiculos.[Tipo de Hibridacion], Vehiculos.[Cantidad Maxima de Pasajeros], Vehiculos.[Tiempo de ensamblaje])"
                 +"VALUES(\""+VIN+"\", "+"\""+Marca+"\", "+"\""+Categoria+"\", "+"\""+Carroceria+"\", "+"\""+NumPuertas+"\", "+"\""+Color+"\", "+"\""+Motor+"\", "+"\""+Precio+"\", "+"\""+""+"\", "+"\""+5+"\", "+"\""+500+"\" )");
         DB.Commit();
        }
        catch (SQLException ex) 
                {
                ex.printStackTrace();
                }
        DB.Disconnect(); 
        AgregandoVehiculo=false;
        }
        
        if(ModificandoVehiculo)
        {
           DatabaseCon DB = new DatabaseCon("./Volkswagen.accdb");
        DB.Connect();
        try
        {
         DB.Query.execute("UPDATE Vehiculos "
                 +"SET Marca=\""+Marca+"\", "
                 +"Categoria=\""+Categoria+"\", "
                 +"Carroceria=\""+Carroceria+"\", "
                 +"[Numero de Puertas]=\""+NumPuertas+"\", "
                 +"Color=\""+Color+"\", "
                 +"[Tipo de Motor]=\""+Motor+"\", "
                 +"Precio=\""+Precio+"\" "
                 +"WHERE VIN=\""+VIN+"\""
                        );
         DB.Commit();
        }
        catch (SQLException ex) 
                {
                ex.printStackTrace();
                }
        DB.Disconnect(); 
        AgregandoVehiculo=false;
        }
        
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        DatabaseCon DB2 = new DatabaseCon("./Volkswagen.accdb");
        DB2.Connect();
        try
        {
         DB2.Query.execute("SELECT Vehiculos.VIN, Vehiculos.Marca, Vehiculos.Categoria, Vehiculos.Carroceria, Vehiculos.[Numero de Puertas], Vehiculos.Color, Vehiculos.[Tipo de Motor], Vehiculos.Precio, Vehiculos.[Tipo de Hibridacion], Vehiculos.[Cantidad Maxima de Pasajeros], Vehiculos.[Tiempo de ensamblaje] FROM Vehiculos ");
         ResultSet Result = DB2.Query.getResultSet();
         
         int i =0;
         while (Result.next()) 
         {
         model.addRow(new Object[]{null,null,null,null,null});
         jTable1.setValueAt(Result.getString(1),i,0);
         jTable1.setValueAt(Result.getString(2),i,1);
         jTable1.setValueAt(Result.getString(3),i,2);
         jTable1.setValueAt(Result.getString(6),i,3);
         jTable1.setValueAt(Result.getString(8),i,4);
         i++;
         } 
         
        }
        catch (SQLException ex) 
                {
                ex.printStackTrace();
                }
        DB2.Disconnect();
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton_GuardarVehiculoMouseClicked

    private void jMenuItem_ModificarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ModificarVehiculoActionPerformed
        // TODO add your handling code here:
        jDialog1.pack();
        jDialog1.setVisible(true);
        jTextField_VIN.enable(false);
        jTextField_VIN.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0)));
        ModificandoVehiculo=true;
    }//GEN-LAST:event_jMenuItem_ModificarVehiculoActionPerformed

    private void jMenuItem_AddDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AddDefaultActionPerformed
        // TODO add your handling code here:
        DatabaseCon DB = new DatabaseCon("./Volkswagen.accdb");
        DB.Connect();
        try
        {
         DB.Query.execute("INSERT INTO Vehiculos(Vehiculos.VIN, Vehiculos.Marca, Vehiculos.Categoria, Vehiculos.Carroceria, Vehiculos.[Numero de Puertas], Vehiculos.Color, Vehiculos.[Tipo de Motor], Vehiculos.Precio, Vehiculos.[Tipo de Hibridacion], Vehiculos.[Cantidad Maxima de Pasajeros], Vehiculos.[Tiempo de ensamblaje])"
                 +"VALUES(\""+"65ACCJENDGJS5"+"\", "+"\""+"Audi"+"\", "+"\""+"Premium"+"\", "+"\""+"Sedan"+"\", "+"\""+4+"\", "+"\""+"Negro"+"\", "+"\""+"Combustion"+"\", "+"\""+82000+"\", "+"\""+""+"\", "+"\""+5+"\", "+"\""+500+"\" )");
         DB.Commit();
        }
        catch (SQLException ex) 
                {
                ex.printStackTrace();
                }
        DB.Disconnect(); 
    }//GEN-LAST:event_jMenuItem_AddDefaultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Carroceria;
    private javax.swing.ButtonGroup buttonGroup_Categoria;
    private javax.swing.ButtonGroup buttonGroup_Color;
    private javax.swing.ButtonGroup buttonGroup_Filtro;
    private javax.swing.ButtonGroup buttonGroup_Marca;
    private javax.swing.ButtonGroup buttonGroup_Motor;
    private javax.swing.JButton jButton_AplicarFiltro;
    private javax.swing.JButton jButton_EliminarFiltro;
    private javax.swing.JButton jButton_GuardarVehiculo;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Atributos;
    private javax.swing.JLabel jLabel_CategoriaTXT;
    private javax.swing.JLabel jLabel_FiltroSeleccionado;
    private javax.swing.JLabel jLabel_FiltroSeleccionadoTXT;
    private javax.swing.JLabel jLabel_MarcaTXT;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_VINTXT;
    private javax.swing.JMenuBar jMenuBar_MenuPrincipal;
    private javax.swing.JMenuItem jMenuItem_AddDefault;
    private javax.swing.JMenuItem jMenuItem_AgregarVehiculo;
    private javax.swing.JMenuItem jMenuItem_BusquedaVIN;
    private javax.swing.JMenuItem jMenuItem_EliminarVehiculo;
    private javax.swing.JMenuItem jMenuItem_ModificarVehiculo;
    private javax.swing.JMenu jMenu_BusquedaManual;
    private javax.swing.JMenu jMenu_Carroceria;
    private javax.swing.JMenu jMenu_Categoria;
    private javax.swing.JMenu jMenu_Color;
    private javax.swing.JMenu jMenu_FiltroMarcas;
    private javax.swing.JMenu jMenu_MenuFiltros;
    private javax.swing.JMenu jMenu_TipoDeMotor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu_ContextMenu;
    private javax.swing.JRadioButton jRadioButtonAtr_Sedan;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Audi;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Bentley;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Blanco;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Bugatti;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Combustion;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Deportivo;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Eletrico;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Familiar;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_FastBack;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Generalista;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_HatchBack;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Lamborghini;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Negro;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Porsche;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Premium;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_SUV;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Seat;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Sedan;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Skoda;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Volkswagen;
    private javax.swing.JRadioButton jRadioButton_ATRBugatti;
    private javax.swing.JRadioButton jRadioButton_AtrAudi;
    private javax.swing.JRadioButton jRadioButton_AtrBentley;
    private javax.swing.JRadioButton jRadioButton_AtrColorBlanco;
    private javax.swing.JRadioButton jRadioButton_AtrColorNegro;
    private javax.swing.JRadioButton jRadioButton_AtrDeportivo;
    private javax.swing.JRadioButton jRadioButton_AtrFamiliar;
    private javax.swing.JRadioButton jRadioButton_AtrFastBack;
    private javax.swing.JRadioButton jRadioButton_AtrGeneralista;
    private javax.swing.JRadioButton jRadioButton_AtrHatchback;
    private javax.swing.JRadioButton jRadioButton_AtrMotorCombustion;
    private javax.swing.JRadioButton jRadioButton_AtrMotorElectrico;
    private javax.swing.JRadioButton jRadioButton_AtrPremium;
    private javax.swing.JRadioButton jRadioButton_AtrSEAT;
    private javax.swing.JRadioButton jRadioButton_AtrSUV;
    private javax.swing.JRadioButton jRadioButton_AtrSkoda;
    private javax.swing.JRadioButton jRadioButton_AtrVolkswagen;
    private javax.swing.JRadioButton jRadioButton_Lambo;
    private javax.swing.JRadioButton jRadioButton_Porsche;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_NumPuertas;
    private javax.swing.JSpinner jSpinner_Precio;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_VIN;
    // End of variables declaration//GEN-END:variables
}
