/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_rafaelajuria;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author rajur
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        //<editor-fold defaultstate="collapsed" desc=" Codigo Adicional - Corre al iniciar el programa ">
        //Llena la tabla con todos los datos
        DatabaseCon DB = new DatabaseCon("./Volkswagen.accdb");
        DB.Connect();
        try
        {
         DB.Query.execute("SELECT Vehiculos.VIN, Vehiculos.Marca, Vehiculos.Categoria, Vehiculos.Carroceria, Vehiculos.[Numero de Puertas], Vehiculos.Color, Vehiculos.[Tipo de Motor], Vehiculos.Precio, Vehiculos.[Tipo de Hibridacion], Vehiculos.[Cantidad Maxima de Pasajeros], Vehiculos.[Tiempo de ensamblaje] FROM Vehiculos");
         ResultSet Result = DB.Query.getResultSet();
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.setRowCount(0);
         int i =0;
         while (Result.next()) 
         {
         model.addRow(new Object[]{null,null,null,null,null});
         jTable1.setValueAt(Result.getString(1),i,0);
         jTable1.setValueAt(Result.getString(2),i,1);
         jTable1.setValueAt(Result.getString(3),i,2);
         jTable1.setValueAt(Result.getString(6),i,3);
         jTable1.setValueAt(Result.getString(8),i,4);
         i++;
         } 
        }
        catch (SQLException ex) 
                {
                ex.printStackTrace();
                }
        DB.Disconnect();
        //</editor-fold>
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Filtro = new javax.swing.ButtonGroup();
        jPopupMenu_ContextMenu = new javax.swing.JPopupMenu();
        jMenuItem_AgregarVehiculo = new javax.swing.JMenuItem();
        jMenuItem_ModificarVehiculo = new javax.swing.JMenuItem();
        jMenuItem_EliminarVehiculo = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Atributos = new javax.swing.JLabel();
        jLabel_VINTXT = new javax.swing.JLabel();
        jTextField_VIN = new javax.swing.JTextField();
        jLabel_MarcaTXT = new javax.swing.JLabel();
        jRadioButton_AtrSEAT = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton_AtrAudi = new javax.swing.JRadioButton();
        jRadioButton_AtrVolkswagen = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton_ATRBugatti = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_FiltroSeleccionadoTXT = new javax.swing.JLabel();
        jLabel_FiltroSeleccionado = new javax.swing.JLabel();
        jButton_AplicarFiltro = new javax.swing.JButton();
        jButton_EliminarFiltro = new javax.swing.JButton();
        jMenuBar_MenuPrincipal = new javax.swing.JMenuBar();
        jMenu_MenuFiltros = new javax.swing.JMenu();
        jMenu_FiltroMarcas = new javax.swing.JMenu();
        jRadioButtonMenuItem_Audi = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Bentley = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Bugatti = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Lamborghini = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Porsche = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Seat = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Skoda = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Volkswagen = new javax.swing.JRadioButtonMenuItem();
        jMenu_Categoria = new javax.swing.JMenu();
        jRadioButtonMenuItem_Generalista = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Premium = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Deportivo = new javax.swing.JRadioButtonMenuItem();
        jMenu_Carroceria = new javax.swing.JMenu();
        jRadioButtonMenuItem_Sedan = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_Familiar = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_HatchBack = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_FastBack = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_SUV = new javax.swing.JRadioButtonMenuItem();
        jMenu_Color = new javax.swing.JMenu();
        jMenu_TipoDeMotor = new javax.swing.JMenu();
        jMenu_BusquedaManual = new javax.swing.JMenu();
        jMenuItem_BusquedaVIN = new javax.swing.JMenuItem();

        jMenuItem_AgregarVehiculo.setText("Agregar");
        jPopupMenu_ContextMenu.add(jMenuItem_AgregarVehiculo);

        jMenuItem_ModificarVehiculo.setText("jMenuItem2");
        jPopupMenu_ContextMenu.add(jMenuItem_ModificarVehiculo);

        jMenuItem_EliminarVehiculo.setText("Eliminar");
        jMenuItem_EliminarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_EliminarVehiculoActionPerformed(evt);
            }
        });
        jPopupMenu_ContextMenu.add(jMenuItem_EliminarVehiculo);

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);

        jLabel_Atributos.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel_Atributos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Atributos.setText("Atributos del Vehiculo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Atributos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Atributos, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel_VINTXT.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_VINTXT.setText("VIN:");

        jLabel_MarcaTXT.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_MarcaTXT.setText("Marca:");

        jRadioButton_AtrSEAT.setText("SEAT");

        jRadioButton2.setText("Skoda");

        jRadioButton_AtrAudi.setText("Audi");

        jRadioButton_AtrVolkswagen.setText("Volkswagen");

        jRadioButton5.setText("Porsche");

        jRadioButton6.setText("Lamborghini");

        jRadioButton_ATRBugatti.setText("Bugatti");

        jRadioButton9.setText("Bentley");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Categoria:");

        jRadioButton8.setText("Generalista");

        jRadioButton10.setText("Premium");

        jRadioButton11.setText("Deportivo");

        jRadioButton15.setText("HatchBack");

        jRadioButton16.setText("FastBack");

        jRadioButton17.setText("SUV");

        jRadioButton18.setText("Familiar");

        jRadioButton19.setText("Sedan");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Carroceria");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Numero de Puertas:");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(2, 2, 5, 1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Color:");

        jRadioButton12.setText("Blanco");

        jRadioButton13.setText("Negro");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Tipo de Motor:");

        jRadioButton14.setText("Combustion");

        jRadioButton20.setText("Electrico");

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(50000.0d, 20000.0d, 500000.0d, 10000.0d));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Precio:");

        jButton1.setText("Guardar");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel_VINTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_VIN, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel_MarcaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_AtrSEAT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_ATRBugatti))
                    .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialog1Layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addComponent(jRadioButton_AtrAudi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton_AtrVolkswagen)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioButton9))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                            .addComponent(jRadioButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton6)))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton8)))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton18))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton20)
                            .addComponent(jRadioButton14)))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton15)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addComponent(jRadioButton16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton17))
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton13)
                            .addComponent(jRadioButton12)))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_VIN)
                    .addComponent(jLabel_VINTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_MarcaTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton_AtrSEAT)
                    .addComponent(jRadioButton_ATRBugatti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_AtrAudi)
                    .addComponent(jRadioButton_AtrVolkswagen)
                    .addComponent(jRadioButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton11))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton19)
                    .addComponent(jRadioButton18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton16)
                    .addComponent(jRadioButton17))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jRadioButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jRadioButton14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel_Titulo.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("Base de datos de Ensamblaje");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "VIN", "Marca", "Categoria", "Color", "Precio"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel_FiltroSeleccionadoTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FiltroSeleccionadoTXT.setText("Filtro Seleccionado:");

        jLabel_FiltroSeleccionado.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel_FiltroSeleccionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FiltroSeleccionado.setText("Ninguno");

        jButton_AplicarFiltro.setText("Aplicar");
        jButton_AplicarFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_AplicarFiltroMouseClicked(evt);
            }
        });

        jButton_EliminarFiltro.setText("Quitar");
        jButton_EliminarFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_EliminarFiltroMouseClicked(evt);
            }
        });

        jMenu_MenuFiltros.setText("Filtros");

        jMenu_FiltroMarcas.setText("Marca");

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Audi);
        jRadioButtonMenuItem_Audi.setText("Audi");
        jMenu_FiltroMarcas.add(jRadioButtonMenuItem_Audi);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Bentley);
        jRadioButtonMenuItem_Bentley.setText("Bentley");
        jMenu_FiltroMarcas.add(jRadioButtonMenuItem_Bentley);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Bugatti);
        jRadioButtonMenuItem_Bugatti.setText("Bugatti");
        jMenu_FiltroMarcas.add(jRadioButtonMenuItem_Bugatti);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Lamborghini);
        jRadioButtonMenuItem_Lamborghini.setText("Lamborghini");
        jMenu_FiltroMarcas.add(jRadioButtonMenuItem_Lamborghini);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Porsche);
        jRadioButtonMenuItem_Porsche.setText("Porsche");
        jMenu_FiltroMarcas.add(jRadioButtonMenuItem_Porsche);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Seat);
        jRadioButtonMenuItem_Seat.setText("SEAT");
        jMenu_FiltroMarcas.add(jRadioButtonMenuItem_Seat);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Skoda);
        jRadioButtonMenuItem_Skoda.setText("Skoda");
        jMenu_FiltroMarcas.add(jRadioButtonMenuItem_Skoda);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Volkswagen);
        jRadioButtonMenuItem_Volkswagen.setText("Volkswagen");
        jMenu_FiltroMarcas.add(jRadioButtonMenuItem_Volkswagen);

        jMenu_MenuFiltros.add(jMenu_FiltroMarcas);

        jMenu_Categoria.setText("Categoria");

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Generalista);
        jRadioButtonMenuItem_Generalista.setText("Generalista");
        jMenu_Categoria.add(jRadioButtonMenuItem_Generalista);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Premium);
        jRadioButtonMenuItem_Premium.setText("Premium");
        jMenu_Categoria.add(jRadioButtonMenuItem_Premium);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Deportivo);
        jRadioButtonMenuItem_Deportivo.setText("Deportivos");
        jMenu_Categoria.add(jRadioButtonMenuItem_Deportivo);

        jMenu_MenuFiltros.add(jMenu_Categoria);

        jMenu_Carroceria.setText("Carroceria");

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Sedan);
        jRadioButtonMenuItem_Sedan.setText("Sedan");
        jMenu_Carroceria.add(jRadioButtonMenuItem_Sedan);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_Familiar);
        jRadioButtonMenuItem_Familiar.setText("Familiar");
        jMenu_Carroceria.add(jRadioButtonMenuItem_Familiar);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_HatchBack);
        jRadioButtonMenuItem_HatchBack.setText("HatchBack");
        jMenu_Carroceria.add(jRadioButtonMenuItem_HatchBack);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_FastBack);
        jRadioButtonMenuItem_FastBack.setText("FastBack");
        jMenu_Carroceria.add(jRadioButtonMenuItem_FastBack);

        buttonGroup_Filtro.add(jRadioButtonMenuItem_SUV);
        jRadioButtonMenuItem_SUV.setText("SUV");
        jMenu_Carroceria.add(jRadioButtonMenuItem_SUV);

        jMenu_MenuFiltros.add(jMenu_Carroceria);

        jMenu_Color.setText("Color");
        jMenu_MenuFiltros.add(jMenu_Color);

        jMenu_TipoDeMotor.setText("Tipo de Motor");
        jMenu_MenuFiltros.add(jMenu_TipoDeMotor);

        jMenuBar_MenuPrincipal.add(jMenu_MenuFiltros);

        jMenu_BusquedaManual.setText("Busqueda");

        jMenuItem_BusquedaVIN.setText("VIN");
        jMenuItem_BusquedaVIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_BusquedaVINActionPerformed(evt);
            }
        });
        jMenu_BusquedaManual.add(jMenuItem_BusquedaVIN);

        jMenuBar_MenuPrincipal.add(jMenu_BusquedaManual);

        setJMenuBar(jMenuBar_MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_FiltroSeleccionadoTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton_AplicarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_EliminarFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                            .addComponent(jLabel_FiltroSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_FiltroSeleccionadoTXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_FiltroSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AplicarFiltro)
                    .addComponent(jButton_EliminarFiltro))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(evt.isMetaDown())
        {
           try
            {
            jPopupMenu_ContextMenu.show(evt.getComponent(), evt.getX(), evt.getY());
            }
            catch(Exception e)
                   {    
                   }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItem_EliminarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_EliminarVehiculoActionPerformed
        // TODO add your handling code here:
        try
        {
        String VIN =String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        DatabaseCon DB = new DatabaseCon("./Volkswagen.accdb");
        DB.Connect();
        try
        {
         DB.Query.execute("DELETE FROM Vehiculos WHERE VIN=\""+VIN+"\"");
         DB.Commit();
        } 
        catch (SQLException ex) 
        {
            ex.printStackTrace();
        }
        DB.Disconnect();
        }
        catch(Exception e)
               {    
               }
    }//GEN-LAST:event_jMenuItem_EliminarVehiculoActionPerformed

    private void jMenuItem_BusquedaVINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_BusquedaVINActionPerformed
        // TODO add your handling code here:
        String VIN = JOptionPane.showInputDialog("Ingrese el VIN que desea ver");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        DatabaseCon DB2 = new DatabaseCon("./Volkswagen.accdb");
        DB2.Connect();
        try
        {
         DB2.Query.execute("SELECT Vehiculos.VIN, Vehiculos.Marca, Vehiculos.Categoria, Vehiculos.Carroceria, Vehiculos.[Numero de Puertas], Vehiculos.Color, Vehiculos.[Tipo de Motor], Vehiculos.Precio, Vehiculos.[Tipo de Hibridacion], Vehiculos.[Cantidad Maxima de Pasajeros], Vehiculos.[Tiempo de ensamblaje] FROM Vehiculos WHERE VIN=\""+VIN+"\"");
         ResultSet Result = DB2.Query.getResultSet();
         
         int i =0;
         while (Result.next()) 
         {
         model.addRow(new Object[]{null,null,null,null,null});
         jTable1.setValueAt(Result.getString(1),i,0);
         jTable1.setValueAt(Result.getString(2),i,1);
         jTable1.setValueAt(Result.getString(3),i,2);
         jTable1.setValueAt(Result.getString(6),i,3);
         jTable1.setValueAt(Result.getString(8),i,4);
         i++;
         } 
         
        }
        catch (SQLException ex) 
                {
                ex.printStackTrace();
                }
        DB2.Disconnect();
    }//GEN-LAST:event_jMenuItem_BusquedaVINActionPerformed

    private void jButton_AplicarFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AplicarFiltroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AplicarFiltroMouseClicked

    private void jButton_EliminarFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_EliminarFiltroMouseClicked
        // TODO add your handling code here:
        DatabaseCon DB = new DatabaseCon("./Volkswagen.accdb");
        DB.Connect();
        try
        {
         DB.Query.execute("SELECT Vehiculos.VIN, Vehiculos.Marca, Vehiculos.Categoria, Vehiculos.Carroceria, Vehiculos.[Numero de Puertas], Vehiculos.Color, Vehiculos.[Tipo de Motor], Vehiculos.Precio, Vehiculos.[Tipo de Hibridacion], Vehiculos.[Cantidad Maxima de Pasajeros], Vehiculos.[Tiempo de ensamblaje] FROM Vehiculos");
         ResultSet Result = DB.Query.getResultSet();
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.setRowCount(0);
         int i =0;
         while (Result.next()) 
         {
         model.addRow(new Object[]{null,null,null,null,null});
         jTable1.setValueAt(Result.getString(1),i,0);
         jTable1.setValueAt(Result.getString(2),i,1);
         jTable1.setValueAt(Result.getString(3),i,2);
         jTable1.setValueAt(Result.getString(6),i,3);
         jTable1.setValueAt(Result.getString(8),i,4);
         i++;
         } 
        }
        catch (SQLException ex) 
                {
                ex.printStackTrace();
                }
        DB.Disconnect();
    }//GEN-LAST:event_jButton_EliminarFiltroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Filtro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_AplicarFiltro;
    private javax.swing.JButton jButton_EliminarFiltro;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Atributos;
    private javax.swing.JLabel jLabel_FiltroSeleccionado;
    private javax.swing.JLabel jLabel_FiltroSeleccionadoTXT;
    private javax.swing.JLabel jLabel_MarcaTXT;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_VINTXT;
    private javax.swing.JMenuBar jMenuBar_MenuPrincipal;
    private javax.swing.JMenuItem jMenuItem_AgregarVehiculo;
    private javax.swing.JMenuItem jMenuItem_BusquedaVIN;
    private javax.swing.JMenuItem jMenuItem_EliminarVehiculo;
    private javax.swing.JMenuItem jMenuItem_ModificarVehiculo;
    private javax.swing.JMenu jMenu_BusquedaManual;
    private javax.swing.JMenu jMenu_Carroceria;
    private javax.swing.JMenu jMenu_Categoria;
    private javax.swing.JMenu jMenu_Color;
    private javax.swing.JMenu jMenu_FiltroMarcas;
    private javax.swing.JMenu jMenu_MenuFiltros;
    private javax.swing.JMenu jMenu_TipoDeMotor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu_ContextMenu;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Audi;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Bentley;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Bugatti;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Deportivo;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Familiar;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_FastBack;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Generalista;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_HatchBack;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Lamborghini;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Porsche;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Premium;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_SUV;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Seat;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Sedan;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Skoda;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_Volkswagen;
    private javax.swing.JRadioButton jRadioButton_ATRBugatti;
    private javax.swing.JRadioButton jRadioButton_AtrAudi;
    private javax.swing.JRadioButton jRadioButton_AtrSEAT;
    private javax.swing.JRadioButton jRadioButton_AtrVolkswagen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_VIN;
    // End of variables declaration//GEN-END:variables
}
